services:
  postgres:
    image: postgres:16-alpine
    container_name: urlshortener-postgres
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: shortener
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shortener -d shortener"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-postgres:
    image: postgres:16-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth -d auth"]
      interval: 5s
      timeout: 5s
      retries: 10

  shortener:
    build:
      context: .
      dockerfile: services/shortener/Dockerfile
    container_name: shortener-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_ADDRESS: ":8080"
      BASE_URL: "http://localhost:3000"
      DATABASE_DSN: "postgres://shortener:shortener@postgres:5432/shortener?sslmode=disable"
      AUTH_ISSUER: "auth-service"
      AUTH_ACCESS_TOKEN_SECRET: "change-me-to-a-long-random-secret-at-least-32-chars"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: auth-service
    depends_on:
      auth-postgres:
        condition: service_healthy
    environment:
      AUTH_SERVER_ADDRESS: ":8081"
      AUTH_ISSUER: "auth-service"
      AUTH_ACCESS_TOKEN_SECRET: "change-me-to-a-long-random-secret-at-least-32-chars"
      AUTH_DATABASE_DSN: "postgres://auth:auth@auth-postgres:5432/auth?sslmode=disable"
      AUTH_COOKIE_SECURE: "false"
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8081/healthz"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: .
      dockerfile: web/frontend/Dockerfile
    container_name: frontend-service
    depends_on:
      auth:
        condition: service_healthy
      shortener:
        condition: service_healthy
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1/app/"]
      interval: 10s
      timeout: 5s
      retries: 10
